  spring:
    datasource:
      url: jdbc.postgresql:/${PGHOST}/${PGPORT}/${PGDATABASE}
      driverClassName: org.postgresql.Driver
      username: ${PGUSER}
      password: ${PGPASSWORD}
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: create


